services:
  bdd-behave:
    image: intel4coro/jupyter-ros2:jazzy-py3.10
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    ports: 
      - 8888:8888
    # privileged: true
    user: root
    working_dir: /home/jovyan/
    command: /bin/bash
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
